"""
render.py

Environment-aware manimgl render invocation for the paper-to-manim-video skill.
Reads the preflight report to determine the render mode, then executes the
appropriate rendering command.

Usage:
    python render.py <scene_file.py> [options]

Options:
    --scene       Scene class name (default: ExplainerVideo)
    --quality     low | medium | hd | uhd (default: hd)
    --output-dir  Directory for output video (default: current dir)
    --server      Override MANIM_SERVER (takes precedence over env var)
    --config      Path to custom_config.yml (default: auto-generated)

Environment variables:
    MANIM_SERVER  user@host for remote server rendering
    DISPLAY       Checked to detect local vs headless mode

Exit codes:
    0  - Render succeeded, video path printed to stdout
    1  - Render failed (with stderr output)
    2  - Preflight report not found (run preflight.py first)
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

USE_COLOR = sys.stdout.isatty()


def _c(code, text):
    """Wrap text in an ANSI escape code if terminal supports colour."""
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text


def bold(t):
    """Return bold text."""
    return _c("1", t)


def green(t):
    """Return green-coloured text."""
    return _c("32", t)


def red(t):
    """Return red-coloured text."""
    return _c("31", t)


def yellow(t):
    """Return yellow-coloured text."""
    return _c("33", t)


# ---------------------------------------------------------------------------
# custom_config.yml writer
# ---------------------------------------------------------------------------

CUSTOM_CONFIG_TEMPLATE = """\
# Auto-generated by paper-to-manim-video render.py
# Optimised for headless video rendering — no interactive window.
directories:
  base: "{output_dir}"
  subdirs:
    output: "."

window:
  full_screen: false

camera:
  background_color: "#0f0f1a"
  fps: 30
  resolution: {resolution}

file_writer:
  ffmpeg_bin: "ffmpeg"
  video_codec: "libx264"
  pixel_format: "yuv420p"

scene:
  show_animation_progress: true
  leave_progress_bars: true
  default_wait_time: 1.0

text:
  font: "DejaVu Sans"
  alignment: "LEFT"
"""

QUALITY_RESOLUTIONS = {
    "low":    "(854, 480)",
    "medium": "(1280, 720)",
    "hd":     "(1920, 1080)",
    "uhd":    "(3840, 2160)",
}

QUALITY_FLAGS = {
    "low":    ["-l"],
    "medium": ["-m"],
    "hd":     ["--hd"],
    "uhd":    ["--uhd"],
}


def write_custom_config(output_dir, quality):
    """
    Write a custom_config.yml optimised for non-interactive rendering.

    Args:
        output_dir: Directory where the video will be written.
        quality: One of 'low', 'medium', 'hd', 'uhd'.

    Returns:
        Path to the written config file.
    """
    resolution = QUALITY_RESOLUTIONS.get(quality, "(1920, 1080)")
    content = CUSTOM_CONFIG_TEMPLATE.format(
        output_dir=output_dir,
        resolution=resolution,
    )
    config_path = os.path.join(output_dir, "custom_config.yml")
    with open(config_path, "w") as f:
        f.write(content)
    return config_path


# ---------------------------------------------------------------------------
# Render mode implementations
# ---------------------------------------------------------------------------

def build_manimgl_cmd(scene_file, scene_class, quality, output_dir, config_path):
    """
    Build the base manimgl command list (mode-agnostic).

    Args:
        scene_file: Path to the Python scene file.
        scene_class: Name of the manim Scene class to render.
        quality: Quality preset string.
        output_dir: Where to write the video.
        config_path: Path to custom_config.yml.

    Returns:
        List of command-line tokens.
    """
    # Prefer python -m manimlib (respects active venv) over bare manimgl binary.
    # A bare 'manimgl' binary on PATH may belong to a different Python installation
    # and won't see the audioop shim or setuptools pin applied in the venv.
    manimgl_module = [sys.executable, "-m", "manimlib"]

    quality_flags = QUALITY_FLAGS.get(quality, ["--hd"])

    cmd = [
        *manimgl_module,
        scene_file,
        scene_class,
        "-w",                        # write to file (no window)
        *quality_flags,
        "--video_dir", output_dir,
        "--config_file", config_path,
        "--quiet",
    ]
    return cmd


def render_local(scene_file, scene_class, quality, output_dir, config_path):
    """
    Render locally using the existing $DISPLAY.

    Args:
        scene_file: Path to scene Python file.
        scene_class: Scene class name.
        quality: Quality preset.
        output_dir: Output directory.
        config_path: Config YAML path.

    Returns:
        Path to rendered MP4.
    Raises:
        RuntimeError on render failure.
    """
    cmd = build_manimgl_cmd(scene_file, scene_class, quality, output_dir, config_path)
    print(bold("\n[render] Mode: local"))
    print(f"[render] Command: {' '.join(cmd)}\n")

    result = subprocess.run(cmd, cwd=os.path.dirname(scene_file) or ".")
    if result.returncode != 0:
        raise RuntimeError(f"manimgl exited with code {result.returncode}")

    return find_output_video(output_dir, scene_class)


def render_headless(scene_file, scene_class, quality, output_dir, config_path):
    """
    Render headlessly using xvfb-run (virtual framebuffer — no physical display needed).

    Args:
        scene_file: Path to scene Python file.
        scene_class: Scene class name.
        quality: Quality preset.
        output_dir: Output directory.
        config_path: Config YAML path.

    Returns:
        Path to rendered MP4.
    Raises:
        RuntimeError on render failure.
    """
    if not shutil.which("xvfb-run"):
        raise RuntimeError(
            "xvfb-run not found. Install with:\n"
            "  sudo apt install xvfb\n"
            "Or set MANIM_SERVER=user@host to use a remote render server."
        )

    manimgl_cmd = build_manimgl_cmd(scene_file, scene_class, quality, output_dir, config_path)
    cmd = [
        "xvfb-run",
        "--auto-servernum",
        "--server-args=-screen 0 1920x1080x24",
        *manimgl_cmd,
    ]

    print(bold("\n[render] Mode: headless (xvfb-run)"))
    print(f"[render] Command: {' '.join(cmd)}\n")

    result = subprocess.run(cmd, cwd=os.path.dirname(scene_file) or ".")
    if result.returncode != 0:
        raise RuntimeError(f"xvfb-run manimgl exited with code {result.returncode}")

    return find_output_video(output_dir, scene_class)


def render_server(scene_file, scene_class, quality, output_dir, config_path, server):
    """
    Render on a remote SSH server, then copy the MP4 back locally.

    Protocol:
        1. Create a temp directory on the server
        2. scp the scene file and config to the server
        3. Execute xvfb-run manimgl on the server
        4. scp the resulting MP4 back to output_dir
        5. Clean up temp directory on server

    Args:
        scene_file: Path to scene Python file.
        scene_class: Scene class name.
        quality: Quality preset.
        output_dir: Local output directory.
        config_path: Config YAML path (local).
        server: user@host string.

    Returns:
        Path to local MP4.
    Raises:
        RuntimeError on any failure.
    """
    print(bold(f"\n[render] Mode: server ({server})"))

    # Create temp dir on the server
    mk_result = subprocess.run(
        ["ssh", server, "mktemp -d /tmp/manim_render_XXXXXX"],
        capture_output=True, text=True, timeout=30,
    )
    if mk_result.returncode != 0:
        raise RuntimeError(f"Could not create temp dir on server {server}:\n{mk_result.stderr}")

    remote_dir = mk_result.stdout.strip()
    print(f"[render] Remote temp dir: {remote_dir}")

    try:
        # Upload scene file and config
        scene_name = os.path.basename(scene_file)
        config_name = os.path.basename(config_path)

        for local, remote in [
            (scene_file, f"{server}:{remote_dir}/{scene_name}"),
            (config_path, f"{server}:{remote_dir}/{config_name}"),
        ]:
            scp = subprocess.run(
                ["scp", local, remote],
                capture_output=True, text=True, timeout=60,
            )
            if scp.returncode != 0:
                raise RuntimeError(f"scp failed for {local}:\n{scp.stderr}")

        print(f"[render] Files uploaded to server")

        # Build and run the render command on server
        quality_flags = " ".join(QUALITY_FLAGS.get(quality, ["--hd"]))
        remote_cmd = (
            f"cd {remote_dir} && "
            f"xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' "
            f"manimgl {scene_name} {scene_class} -w {quality_flags} "
            f"--video_dir {remote_dir} "
            f"--config_file {remote_dir}/{config_name} "
            f"--quiet"
        )

        print(f"[render] Running on server: {server}")
        ssh_result = subprocess.run(
            ["ssh", server, remote_cmd],
            timeout=1800,  # 30 minute max render time
        )
        if ssh_result.returncode != 0:
            raise RuntimeError(f"Remote render failed (exit code {ssh_result.returncode})")

        # Find the output file on the server
        find_result = subprocess.run(
            ["ssh", server, f"find {remote_dir} -name '*.mp4' | head -1"],
            capture_output=True, text=True, timeout=30,
        )
        remote_video = find_result.stdout.strip()
        if not remote_video:
            raise RuntimeError("No MP4 found on server after render.")

        print(f"[render] Remote video: {remote_video}")

        # Copy back
        local_video = os.path.join(output_dir, f"{scene_class}.mp4")
        scp = subprocess.run(
            ["scp", f"{server}:{remote_video}", local_video],
            capture_output=True, text=True, timeout=300,
        )
        if scp.returncode != 0:
            raise RuntimeError(f"Could not copy video back from server:\n{scp.stderr}")

        print(green(f"[render] Video copied to: {local_video}"))
        return local_video

    finally:
        # Always clean up remote temp dir
        subprocess.run(
            ["ssh", server, f"rm -rf {remote_dir}"],
            capture_output=True, timeout=30,
        )
        print(f"[render] Remote temp dir cleaned up")


# ---------------------------------------------------------------------------
# Output video finder
# ---------------------------------------------------------------------------

def find_output_video(output_dir, scene_class):
    """
    Find the MP4 that manimgl wrote to output_dir.

    manimgl names files like: ExplainerVideo.mp4 or ExplainerVideo_hd.mp4, etc.

    Args:
        output_dir: Directory to search.
        scene_class: Scene class name for matching.

    Returns:
        Path to the MP4 file.
    Raises:
        RuntimeError if no MP4 found.
    """
    import glob
    candidates = glob.glob(os.path.join(output_dir, "**", "*.mp4"), recursive=True)
    # Prefer files containing the scene class name
    matches = [f for f in candidates if scene_class.lower() in os.path.basename(f).lower()]
    if matches:
        return sorted(matches, key=os.path.getmtime)[-1]  # most recent
    if candidates:
        return sorted(candidates, key=os.path.getmtime)[-1]
    raise RuntimeError(
        f"No MP4 found in {output_dir} after render.\n"
        "Check manimgl output above for errors."
    )


# ---------------------------------------------------------------------------
# Main render entry point
# ---------------------------------------------------------------------------

def render(
    scene_file,
    scene_class="ExplainerVideo",
    quality="hd",
    output_dir=None,
    mode_override=None,
    server_override=None,
    config_path=None,
):
    """
    Render a manim scene file to MP4, auto-detecting the best render mode.

    Args:
        scene_file: Path to the Python scene file.
        scene_class: Name of the Scene subclass to render.
        quality: 'low' | 'medium' | 'hd' | 'uhd'.
        output_dir: Where to write the output MP4 (defaults to scene file dir).
        mode_override: Force 'local', 'headless', or 'server'.
        server_override: Explicit user@host (overrides MANIM_SERVER env var).
        config_path: Path to custom_config.yml (auto-generated if None).

    Returns:
        Absolute path to the rendered MP4.
    Raises:
        RuntimeError on failure.
    """
    scene_file = os.path.abspath(scene_file)
    if not os.path.isfile(scene_file):
        raise FileNotFoundError(f"Scene file not found: {scene_file}")

    output_dir = output_dir or os.path.dirname(scene_file)
    os.makedirs(output_dir, exist_ok=True)

    # Load preflight report if available
    preflight_report = {}
    report_path = "/tmp/manim_preflight_report.json"
    if os.path.isfile(report_path):
        with open(report_path) as f:
            preflight_report = json.load(f)

    # Determine render mode
    server = server_override or os.environ.get("MANIM_SERVER", "")
    if mode_override:
        mode = mode_override
    elif server:
        mode = "server"
    elif preflight_report.get("render_mode"):
        mode = preflight_report["render_mode"]
    elif os.environ.get("DISPLAY"):
        mode = "local"
    else:
        mode = "headless"

    print(f"[render] Scene file : {scene_file}")
    print(f"[render] Scene class: {scene_class}")
    print(f"[render] Quality    : {quality}")
    print(f"[render] Output dir : {output_dir}")
    print(f"[render] Mode       : {mode}")

    # Write custom config
    if config_path is None:
        config_path = write_custom_config(output_dir, quality)
        print(f"[render] Config     : {config_path} (auto-generated)")
    else:
        print(f"[render] Config     : {config_path}")

    # Dispatch to render mode
    if mode == "local":
        video_path = render_local(scene_file, scene_class, quality, output_dir, config_path)
    elif mode == "headless":
        video_path = render_headless(scene_file, scene_class, quality, output_dir, config_path)
    elif mode == "server":
        if not server:
            raise RuntimeError(
                "Server mode requires MANIM_SERVER env var or --server flag.\n"
                "Example: export MANIM_SERVER=user@render-host"
            )
        video_path = render_server(scene_file, scene_class, quality, output_dir, config_path, server)
    else:
        raise ValueError(f"Unknown render mode: {mode!r}")

    print(green(bold(f"\n[render] Done! Video written to:\n  {video_path}\n")))
    return video_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    """Entry point for CLI usage."""
    parser = argparse.ArgumentParser(
        description="Render a manimgl scene file to MP4.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              # Auto-detect mode (local or headless):
              python render.py explainer_video.py

              # Force headless (e.g. SSH session):
              python render.py explainer_video.py --mode headless

              # Render on a remote GPU server:
              python render.py explainer_video.py --server user@gpu-host --quality uhd

              # Low-quality fast preview:
              python render.py explainer_video.py --quality low
        """),
    )
    parser.add_argument("scene_file", help="Path to the Python scene file")
    parser.add_argument(
        "--scene", default="ExplainerVideo",
        help="Scene class name (default: ExplainerVideo)",
    )
    parser.add_argument(
        "--quality", choices=["low", "medium", "hd", "uhd"], default="hd",
        help="Render quality (default: hd)",
    )
    parser.add_argument(
        "--output-dir", default=None,
        help="Output directory for the MP4 (default: same dir as scene file)",
    )
    parser.add_argument(
        "--mode", choices=["auto", "local", "headless", "server"], default="auto",
        help="Force a render mode (default: auto-detect)",
    )
    parser.add_argument(
        "--server", default=None,
        help="Remote server for server mode (user@host), overrides MANIM_SERVER env var",
    )
    parser.add_argument(
        "--config", default=None,
        help="Path to custom_config.yml (auto-generated if not provided)",
    )
    args = parser.parse_args()

    try:
        video_path = render(
            scene_file=args.scene_file,
            scene_class=args.scene,
            quality=args.quality,
            output_dir=args.output_dir,
            mode_override=None if args.mode == "auto" else args.mode,
            server_override=args.server,
            config_path=args.config,
        )
        print(video_path)  # machine-readable final line
    except (RuntimeError, FileNotFoundError) as e:
        print(red(f"\nERROR: {e}\n"), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
